version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: sqlite:latest
    volumes:
      - ./estimations.db:/estimations.db
